/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Bakery = IDL.Record({
  'categories' : IDL.Vec(Category),
  'name' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createBakery' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getBakery' : IDL.Func([IDL.Text], [Bakery], ['query']),
  'listBakeries' : IDL.Func([], [IDL.Vec(Bakery)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Bakery = IDL.Record({
    'categories' : IDL.Vec(Category),
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createBakery' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getBakery' : IDL.Func([IDL.Text], [Bakery], ['query']),
    'listBakeries' : IDL.Func([], [IDL.Vec(Bakery)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };